name: Build Windows EXE (no release)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller pyinstaller-hooks-contrib

      - name: Build EXE (PyInstaller one-folder, include plugins)
        shell: pwsh
        run: |
          # 生成可执行文件（文件夹形式，包含所有依赖）
          # 入口脚本为 run.py；图标位于 video2srt/gui/icon.ico
          pyinstaller --noconfirm --clean `
            --name Video2SRT `
            --icon video2srt/gui/icon.ico `
            --onedir `
            --add-data "config/default_config.json;config" `
            --add-data "video2srt/plugins;video2srt/plugins" `
            --collect-submodules video2srt `
            --collect-submodules video2srt.plugins `
            --collect-submodules whisper `
            --collect-submodules torch `
            --collect-submodules PyQt6 `
            run.py

      - name: Download FFmpeg and copy to dist
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          $ffmpegUrl = "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip"
          $zipPath = "ffmpeg.zip"
          Write-Host "Downloading FFmpeg from $ffmpegUrl"
          Invoke-WebRequest -Uri $ffmpegUrl -OutFile $zipPath
          Expand-Archive -Path $zipPath -DestinationPath "ffmpeg" -Force
          $ffmpegExe = Get-ChildItem -Recurse -File ffmpeg | Where-Object { $_.Name -eq "ffmpeg.exe" } | Select-Object -First 1
          $ffprobeExe = Get-ChildItem -Recurse -File ffmpeg | Where-Object { $_.Name -eq "ffprobe.exe" } | Select-Object -First 1
          if (-not $ffmpegExe) { throw "ffmpeg.exe not found in extracted archive" }
          New-Item -ItemType Directory -Force -Path "dist\Video2SRT" | Out-Null
          Copy-Item $ffmpegExe.FullName -Destination "dist\Video2SRT\"
          if ($ffprobeExe) { Copy-Item $ffprobeExe.FullName -Destination "dist\Video2SRT\" }

      - name: List build outputs
        shell: pwsh
        run: |
          Get-ChildItem -Recurse dist\Video2SRT | Format-List

      - name: Create ZIP package
        shell: pwsh
        run: |
          Compress-Archive -Path dist\Video2SRT\* -DestinationPath dist\Video2SRT.zip

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Video2SRT-windows
          path: |
            dist/Video2SRT/Video2SRT.exe
            dist/Video2SRT.zip